name: Pull Request Labels
on:
  pull_request:
    branches:
      - 'dev'
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver:major, semver:minor, semver:patch"
          add_comment: true