name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION  

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🧯 Fixes'
    labels:
      - 'fix'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🛠 Other'

exclude-labels:
  - 'ignore'

autolabeler:
  - label: 'feature'
    title:
      - '/^add/i'
  - label: 'fix'
    title:
      - '/^fix/i'
  - label: 'test'
    title:
      - '/^test/i'
  - label: 'major'
    title:
      - '/^drop/i'
  - label: 'minor'
    title:
      - '/^add/i'
  - label: 'patch'
    title:
      - '/^(cut)|(fix)|(test)|(bump)|(make)|(optimize)|(refactor)|(reformat)|(document)/i'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch