name: "Get Release Draft"
description: "Fetch the most recent draft release's data"
inputs:
  github-token:
    description: "GitHub token"
    required: true
outputs:
  version:
    description: "Release version"
  tag_name:
    description: "Release tag name"
runs:
  using: "node20"
  main: "main.js"