name: "Get Release Draft"
description: "Fetch the latest draft release name from a GitHub repository"
inputs:
  github-token:
    description: "GitHub token"
    required: true
outputs:
  version:
    description: "Version of the latest draft release"
runs:
  using: "node20"
  main: "main.js"