name: PR Auto Labeler

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-labels:
    name: 'Apply labels to PR'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: master