name: 'Dev - PR Label Checker'

on:
  pull_request:
    branches:
      - 'dev'
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check_labels:
    name: 'Check Dev PR Labels'
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
          add_comment: true