name: Release Notes Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-notes:
    name: 'Build release notes'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: master