name: Release Candidate

on: workflow_dispatch

env:
  HUSKY: '0'

jobs:
  release_candidate:
    name: 'Create release candidate'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Branch Name
        uses: ./.github/actions/verify-branch-name
        with:
          name: "master"

      - name: Git config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions    

      - name: Get Release Options
        id: release_options
        uses: ./.github/actions/get-release-options
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: refactor to action
      - name: Apply version bump
        run: |
          CURRENT_VERSION=${{ steps.release_options.outputs.current_version }}
          CURRENT_TAG=${{ steps.release_options.outputs.current_tag }}
          npm version $CURRENT_VERSION -m "Bump to version %s" --no-git-tag-version
          git push
          git push origin $CURRENT_TAG --force

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: master
          version: ${{ steps.release_options.outputs.current_version }}
          prerelease: true
          publish: true

      - name: Create release branch
        run: |
          CURRENT_TAG=${{ steps.release_options.outputs.current_tag }}
          git checkout -b release/$CURRENT_TAG
          git push origin release/$CURRENT_TAG

      - name: Summary
        run: |
          CURRENT_TAG=${{ steps.release_options.outputs.current_tag }}
          echo "## 🎉 Release [$CURRENT_TAG](https://github.com/feliksmatsko/cicd/releases/tag/$CURRENT_TAG) successfully created" >> $GITHUB_STEP_SUMMARY