name: 'Dev - PR Close Version Bump'

on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed

jobs:
  bump-version:
    name: 'Bump Version on develop'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      #      - name: Git config
      #        run: |
      #          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
      #          git config --global user.name "${{ secrets.GH_ORG_NAME }}"

      - name: List directory
        run: ls -al

      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: npm version major

      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm version minor

      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: npm version patch

      - name: Git push version bump
        run: git push origin dev --follow-tags --force

      - id: set-version
        name: Output version change
        run: npm pkg get version